### PR TITLE
Add ML Model APIs

### PR DESCRIPTION
**Pull request by adeelFeroz77**

### CODE REVIEW

**Comment by adeelFeroz77** [comment]
Will refactor user_plant_routes, once I'm done with the flows.

**Comment by HarisKhan15** [comment]
Ok noted

**Review by HarisKhan15 — APPROVED** [review]

**Review by waniaJamal11 — APPROVED** [review]

**Comment by HarisKhan15** [comment]
Approved, But make PR for develop not for main

**Comment by adeelFeroz77** [comment]
Changed Destination Branch to Develop.

**Pull request merged**
